// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Word_Game.Infrastructure.Persistance;

#nullable disable

namespace Word_Game.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Word_Game.Domain.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Coins")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42d2a78b-3b29-4c73-8495-4177a872828a"),
                            Coins = 2L,
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("aaef71b2-750a-42c6-ae6d-9e5ab5e2c1ab"),
                            Coins = 4L,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("f7c92048-4153-4b64-9466-0693b90b8396"),
                            Coins = 6L,
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("Word_Game.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("Coins")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec1370b9-7780-45f3-b43b-c2ab10ee26b0"),
                            Coins = 0L,
                            IsAdmin = true,
                            Password = "google_admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Word_Game.Domain.Entities.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LevelId")
                        .HasColumnType("uuid");

                    b.Property<string>("_Word")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Word_Game.Domain.Entities.Word", b =>
                {
                    b.HasOne("Word_Game.Domain.Entities.Level", null)
                        .WithMany("Words")
                        .HasForeignKey("LevelId");
                });

            modelBuilder.Entity("Word_Game.Domain.Entities.Level", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
